name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: server connaction
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.SERVER_HOST }} 
        username: ${{ secrets.SERVER_USERNAME }} 
        password: ${{ secrets.SERVER_PASSWORD }}
        script: | 
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -

          cd /home/muhammadamin/cicd-tutorial

          git stash
          git pull origin main

          npm install
          npm run build

          echo "✅ Deployment tugadi!"